wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.15.12
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1698428086.965773
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.11.6
      5: 0.15.12
      8:
      - 1
      - 5
      13: linux-x86_64
