wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.35.0.dev0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1698522120.099777
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 84
      - 98
      3:
      - 23
      4: 3.11.6
      5: 0.15.12
      6: 4.35.0.dev0
      8:
      - 1
      - 5
      13: linux-x86_64
